# Render configuration file
services:
  # Backend API service
  - type: web
    name: ecommerce-api
    env: docker
    dockerfilePath: docker/Dockerfile.server
    dockerContext: .
    plan: starter
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          name: ecommerce-client
          type: web
          property: url
      - key: MONGODB_URI
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: SEED_DATABASE
        value: false # Set to true for first deployment, then false

  # Frontend static site
  - type: web
    name: ecommerce-client
    env: docker
    dockerfilePath: docker/Dockerfile.client
    dockerContext: .
    plan: starter
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: ecommerce-api
          type: web
          property: url
      - key: REACT_APP_NODE_ENV
        value: production

# Database
databases:
  - name: ecommerce-db
    plan: starter
    databaseName: ecommerce
