FROM node:23-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Create directories for placeholder images
RUN mkdir -p public/images/products public/images/categories

# Create placeholder images
RUN echo "Placeholder" > public/images/products/placeholder.jpg && \
    echo "Placeholder" > public/images/categories/placeholder.jpg

EXPOSE 3000

CMD ["npm", "run", "dev"]